# 3EF Studio – Global Context
brand:
  name: "Three Eagles Forge Studio"
  short_name: "3EF Studio"
  tagline: "Ship small. Learn fast. Soar Higher."
  logo:
    light: "/logo/light.svg"
    dark: "/logo/dark.svg"
    favicon: "/favicon.svg"
  colors:
    background: "#0B0F14"
    card: "#11161C"
    text: "#E7ECF2"
    muted: "#9FB0C0"
    accent: "#5EEAD4"
    accent2: "#60A5FA"
  fonts:
    heading: "Inter, ui-sans-serif, system-ui, -apple-system, Segoe UI, Roboto, Helvetica, Arial, Noto Sans, 'Apple Color Emoji', 'Segoe UI Emoji'"
    body: "Inter, ui-sans-serif, system-ui, -apple-system, Segoe UI, Roboto, Helvetica, Arial, Noto Sans"
    scale:
    xs: "0.75rem"
    sm: "0.875rem"
    base: "1rem"
    lg: "1.125rem"
    xl: "1.25rem"
    "2xl": "1.5rem"
    "3xl": "1.875rem"
    "4xl": "2.25rem"
radii:
  xl: "1rem"
  2xl: "1.25rem"
motion:
  hover: "200ms"
  enter: "250ms"


flags:
dark_mode_default: true
show_products_teaser: true

env:
  newsletter_provider: "buttondown"
  analytics_provider: "plausible"
  hosting: "vercel"
  domain: "3ef.studio"

features:
  blog: true
  products_page: false
  analytics: false
  newsletter_form: true
  mdx_enabled: false
  ai_agents_phase: 0  # future flag

meta:
  version: "v0.1.0-site-mvp"
  last_updated: "2025-10-28"
  next_sprint: "sprint-2-content-newsletter"
