// app/newsletter/domains/page.tsx

import {
  getLatestDdeIssueMeta,
  getLatestDdePreviewTop5,
} from "@/lib/newsletter/dde";

import DDENewsletterForm from "@/components/DDENewsletterForm";

export const metadata = {
  title: "DDE Weekly Top Domains — 3EF",
  description:
    "A weekly list of curated, currently available brandable domains discovered by the 3EF Domain Discovery Engine.",
  alternates: { canonical: "/newsletter/domains" },
};

function formatPrice(value: number | null | undefined): string {
  if (value == null || Number.isNaN(value)) return "-";
  return `$${value.toLocaleString()}`;
}

function formatScore(value: number | null | undefined): string {
  if (value == null || Number.isNaN(value)) return "-";
  return value.toFixed(2);
}

export default async function DdeNewsletterPage() {
  const meta = getLatestDdeIssueMeta();
  const preview = getLatestDdePreviewTop5();
  const hasIssue = !!meta && preview.length > 0;

  return (
    <div className="mx-auto max-w-4xl space-y-16 px-4 py-16">
      {/* ---------------- Hero ---------------- */}
      <section className="space-y-4 text-center">
        <h1 className="text-3xl font-semibold tracking-tight">
          DDE Weekly Top Domains
        </h1>
        <p className="mx-auto max-w-2xl text-muted-foreground">
          A weekly list of currently available brandable domains for founders,
          indie hackers, and small teams. Generated by the Domain Discovery
          Engine and graded with type-aware pricing.
        </p>
        <div className="flex flex-wrap items-center justify-center gap-3">
          <a
            href="#subscribe"
            className="inline-block rounded-xl bg-accent px-5 py-3 font-medium text-black shadow-sm transition hover:opacity-90"
          >
            Get the full weekly list by email
          </a>
          {hasIssue && (
            <a
              href="#preview"
              className="inline-block rounded-xl border border-border px-5 py-3 text-sm font-medium text-foreground shadow-soft hover:bg-card/80 transition"
            >
              See this week&apos;s Top 5
            </a>
          )}
        </div>
      </section>

      {/* ---------------- What You Get ---------------- */}
      <section className="space-y-6">
        <h2 className="text-xl font-semibold">What You Get</h2>
        <ul className="grid gap-6 md:grid-cols-3">
          <li className="rounded-2xl bg-card p-5 shadow-soft">
            <h3 className="font-medium">Curated & Available</h3>
            <p className="text-sm text-muted-foreground">
              Fresh DDE runs filtered for current availability and diversity.
              No hypothetical names—only domains you can actually register or
              buy.
            </p>
          </li>
          <li className="rounded-2xl bg-card p-5 shadow-soft">
            <h3 className="font-medium">Scored, Graded, Typed</h3>
            <p className="text-sm text-muted-foreground">
              Each domain has a heuristic score, an LLM grade (Strong Buy / Buy
              / Watchlist), and a type label like{" "}
              <span className="font-mono text-xs">
                coined_tech_brandable
              </span>{" "}
              or{" "}
              <span className="font-mono text-xs">two_word_descriptive</span>.
            </p>
          </li>
          <li className="rounded-2xl bg-card p-5 shadow-soft">
            <h3 className="font-medium">Type-Aware Pricing</h3>
            <p className="text-sm text-muted-foreground">
              Suggested pricing takes into account grade, TLD, length, and type
              so short premium and broad brandables surface appropriately.
            </p>
          </li>
        </ul>
      </section>

      {/* ---------------- This Week's Top 5 Preview ---------------- */}
      <section id="preview" className="space-y-4">
        <div className="flex flex-col gap-2 md:flex-row md:items-end md:justify-between">
          <div className="space-y-1">
            <h2 className="text-xl font-semibold">This Week&apos;s Top 5</h2>
            <p className="text-sm text-muted-foreground">
              The full issue typically includes 15–20 domains with scores,
              types, and pricing. Below is the public Top 5 preview for the
              latest run.
            </p>
          </div>
          {meta && (
            <div className="text-sm text-muted-foreground">
              {meta.shortlistSize} domains · price range{" "}
              {formatPrice(meta.priceMin)}–{formatPrice(meta.priceMax)} · avg{" "}
              {formatPrice(meta.priceAvg)}
            </div>
          )}
        </div>

        {!hasIssue && (
          <p className="text-sm text-muted-foreground">
            The first issue hasn&apos;t been published yet. Once the pipeline
            runs, you&apos;ll see the latest Top 5 preview here.
          </p>
        )}

        {hasIssue && (
          <div className="overflow-x-auto rounded-2xl bg-card p-5 shadow-soft">
            <table className="min-w-full text-left text-sm">
              <thead>
                <tr className="border-b border-border/70">
                  <th className="pb-2 pr-4 font-semibold">Domain</th>
                  <th className="pb-2 pr-4 font-semibold">Type</th>
                  <th className="pb-2 pr-4 font-semibold">Grade</th>
                  <th className="pb-2 pr-4 font-semibold">Price</th>
                  <th className="pb-2 pr-4 font-semibold">Score</th>
                  <th className="pb-2 pr-4 font-semibold">Note</th>
                </tr>
              </thead>
              <tbody>
                {preview.map((d) => (
                  <tr
                    key={d.domain}
                    className="border-b border-border/40 last:border-0"
                  >
                    <td className="py-2 pr-4 font-medium">{d.domain}</td>
                    <td className="py-2 pr-4 text-xs font-mono text-muted-foreground">
                      {d.type}
                    </td>
                    <td className="py-2 pr-4 text-sm">{d.grade}</td>
                    <td className="py-2 pr-4 text-sm">
                      {formatPrice(d.price_suggested)}
                    </td>
                    <td className="py-2 pr-4 text-sm">
                      {formatScore(d.final_score)}
                    </td>
                    <td className="py-2 pr-4 text-sm text-muted-foreground">
                      {d.insight}
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        )}

        <p className="text-sm text-muted-foreground">
          Want the full list and extended notes (typically 15–20 domains per
          issue)? Subscribe below and get the complete issue by email.
        </p>
      </section>

      {/* ---------------- Subscribe ---------------- */}
      <section id="subscribe" className="space-y-4">
        <h2 className="text-xl font-semibold">Get the Full Weekly List</h2>
        <p className="text-sm text-muted-foreground max-w-2xl">
          Each week, you&apos;ll receive the full DDE shortlist with scores,
          types, pricing, and notes. No spam, no resale of your email—just
          speculative naming ideas and the occasional 3EF studio update.
        </p>

        <DDENewsletterForm source="DDE Newsletter" />

        <p className="text-xs text-muted-foreground">
          This is not financial advice. Domain availability and pricing are
          heuristic and can change at any time.
        </p>
      </section>

      <section className="text-center">
        <a
            href="/newsletter/domains/archive"
            className="text-sm text-muted-foreground underline-offset-2 hover:underline"
        >
            View all past issues →
        </a>
      </section>
    </div>
  );
}
